# EMECDRV SPECIFIC DEFINES

TITAN40_EMECDRV5_LIFT_NODE_ID = 0x0C
TITAN40_EMECDRV5_SLEWING_NODE_ID = 0x0D

#  TARGET POSITIONS FOR TESTING MOVEMENT (NOTE: CHANGE MIN/MAX TIME IF TARGET CHANGES)
MIN_TARGET_POSITION_LIFT = 0  # 0% LIFT POSITION
MAX_TARGET_POSITION_LIFT = 100  # 100% LIFT POSITION
MIN_TARGET_POSITION_SLEWING = -100
MAX_TARGET_POSITION_SLEWING = 1900

MIN_POS_PER_SECOND_LIFT = 2  # MINIMUM POSITION PER SECOND NEED FOR MOVEMENT DETECTION
MIN_POS_PER_SECOND_SLEWING = 7

#  MIN AND MAX TIME FOR MOVEMENT
MIN_MOVEMENT_TIME_LIFT = 20
MAX_MOVEMENT_TIME_LIFT = 65

MAX_MOVEMENT_TIME_ABSOLUTE_LIFT = 500
MAX_MOVEMENT_TIME_ABSOLUTE_SLEWING = 500

OD_MANUFACTURER_DEVICE_NAME = 0x1008
OD_MANUFACTURER_HARDWARE_VERSION = 0x1009
OD_MANUFACTURER_SOFTWARE_VERSION = 0x100A
OD_DEVICE_ERROR_FLAGS = 0x2100

OD_MODES_OF_OPERATION = 0x6060
OD_POSITION_ACTUAL_VALUE = 0x6064
OD_MAX_CURRENT = 0x6073
OD_MOTOR_RATED_CURRENT = 0x6075
OD_CURRENT_ACTUAL_VALUE = 0x6078  # factor = OD_MOTOR_RATED_CURRENT / 1000
OD_DC_LINK_CIRCUIT_VOLTAGE = 0x6079  # Battery voltage
OD_TARGET_POSITION = 0x607A

OD_STATUS_WORD = 0x6041
OD_CONTROL_WORD = 0x6040

# STATUS WORD MASK
STATUS_READY_TO_SWITCH_ON = 0x0
STATUS_READY = 0x02
STATUS_OPERATION_ENABLED = 0x04
STATUS_FAULT = 0x08
STATUS_VOLTAGE_ENABLED = 0x10
STATUS_QUICK_STOP = 0x20
STATUS_SWITCH_ON_INHIBIT = 0x40
STATUS_WARNING_ACTIVE = 0x80
STATUS_START_FUNCTION = 0x100
STATUS_BUS_CONTROL_EN = 0x200
STATUS_TARGET_REACHED = 0x400
STATUS_INTERNAL_LIMIT_EXCEEDED = 0x800

# CONTROL WORD MASK
CONTROL_READY = 0x0
CONTROL_DISABLE_VOLTAGE = 0x02
CONTROL_QUICK_STOP = 0x04
CONTROL_ENABLE_OPERATION = 0x08
CONTROL_OPERATING_MODE_CUSTOM_1 = 0x10
CONTROL_START_MOVEMENT_ORDER = 0x10
CONTROL_OPERATING_MODE_CUSTOM_2 = 0x20
CONTROL_OPERATING_MODE_CUSTOM_3 = 0x40
CONTROL_ACK_ERROR = 0x80
CONTROL_STOP = 0x100

# Operating modes
PROFILE_POSITION_OPERATING_MODE = 0x01
VELOCITY_OPERATING_MODE = 0x02
PROFILE_VELOCITY_OPERATING_MODE = 0x03
PROFILE_TORQUE_OPERATING_MODE = 0x04
HOMING_OPERATING_MODE = 0x06

STOPPED = 0
CW = 1
CCW = 2