/*
 * cal_conf.h - CANopen Library Configuration
 *
 * Copyright (C) 1998-2015  by port GmbH  Halle(Saale)/Germany
 *
 *------------------------------------------------------------
 * This file was generated by the CANopen Design Tool V2.3.6.0
 * from project C:/00_WORK/10_Pro/99_Automation_dpt/90_SNOW_GUN/E-MEC/CanOpen_Slave/Slave_06/Slave_06.can
 * on 2023/02/16 at 10:32:10.
 */

/**
 * \file cal_conf.h
 * \author port GmbH
 *
 * This module contains the configuration
 * of the CANopen Library for the CANopen device.
 */



#ifndef CAL_CONF_H
#define CAL_CONF_H	1
#define CO_CONFIG_DESIGNTOOL_VERSION 0x0203

/* active configuration : 0 */
#define CO_CONFIG_USE_TARGET_0 1


/*
 * General Settings
 */
#define CONFIG_CAN_ERROR_HANDLING      	1
#define CONFIG_FAST_SORT               	1
#define CONFIG_LARGE_TIMER             	1
#define CONFIG_SLAVE                   	1
#define CO_LIB_INIT_VAR			
#define CO_DT_INIT_VAR			
#define CO_LIB_UNINIT_VAR		
#define CONFIG_CAN_OBJECTS             	9

/*
 * Hardware configuration 0: 0
 */


/*
 * Code Maturity Level Options
 */


/*
 * CPU Setup
 */
#ifdef CO_CONFIG_USE_TARGET_0
#define CONFIG_COLIB_TIMER                  	1
#define CONFIG_CPU_FAMILY_GENERIC           	1
#define CONFIG_TIMER_INC                    	500

# ifdef DEF_HW_PART
#  include <cpu_generic.h>
# endif /* DEF_HW_PART */

#endif /* CO_CONFIG_USE_TARGET_0*/


/*
 * CAN Controller Setup
 */
#ifdef CO_CONFIG_USE_TARGET_0
#define CONFIG_CAN_FAMILY_GENERIC           	1
#define CONFIG_COLIB_BUFFER                 	1
#define CONFIG_COLIB_FLUSHMBOX              	1
#define CONFIG_FLUSHMBOX_READ_MAXMSG        	10
#define CONFIG_RX_BUFFER_SIZE               	10
#define CONFIG_TX_BUFFER_SIZE               	10
#define CONFIG_CAN_START_TYPE               	1
#define CONFIG_CAN_ACCESS_MEM_MAP           	1
#define CONFIG_CAN_REGISTER_OFFSET          	1
#define CONFIG_CAN_USE_MEMCPY               	1
#define CONFIG_STANDARD_IDENTIFIER          	1
#endif /* CO_CONFIG_USE_TARGET_0*/


/*
 * Compiler Setup
 */
#ifdef CO_CONFIG_USE_TARGET_0
#define CONFIG_ALIGNMENT                    	1
#define CONFIG_CLEAR_CO_GLOBAL_VARS         	co_generic.h
#define CONFIG_COMPILER_GENERIC             	1
#endif /* CO_CONFIG_USE_TARGET_0 */




/*
 * CANopen Services
 */
#define CONFIG_DYN_PDO_MAPPING         	1
#define CONFIG_HEARTBEAT_CONSUMER      	1
#define CONFIG_HEARTBEAT_PRODUCER      	1
#define CONFIG_MAPPING_CNT             	24
#define CONFIG_NODE_GUARDING           	1
#define CONFIG_NON_VOLATILE_MEM        	1
#define CONFIG_PDO_CONSUMER            	1
#define CONFIG_PDO_EVENTTIMER          	1
#define CONFIG_PDO_PRODUCER            	2
#define CONFIG_RPDO_MAPPING_CNT        	8
#define CONFIG_SDO_SERVER              	1
#define CONFIG_SYNC_CONSUMER           	1
#define CONFIG_TPDO_MAPPING_CNT        	16
/*
 * Additional CANopen Settings
 */
#define CONFIG_CONST_OBJDIR            	1

/* 
 * special DEFINE part - don't edit here, it is changed by the DesignTool 
 */
#define CO_CONFIG_SPECIAL_START	1



#define CO_CONFIG_SPECIAL_END	1

/* 
 * user specific part - will not be changed by the DesignTool
 */
#define CO_CONFIG_USER_SPEC_START	1

#define CO_CONFIG_USER_SPEC_END	1

#endif /* CAL_CONF_H */
