/*
 * objects.h - Object dictionary
 *
 * Copyright (C) 1998-2015  by port GmbH  Halle(Saale)/Germany
 *
 *------------------------------------------------------------
 * This file was generated by the CANopen Design Tool V2.3.6.0
 * from project C:/00_WORK/10_Pro/99_Automation_dpt/90_SNOW_GUN/E-MEC/CanOpen_Slave/Slave_06/Slave_06.can
 * on 2023/02/16 at 10:32:10.
 */

/**
 * \file objects.h
 * \author port GmbH
 *
 * This module contains the object dictionary
 * of the CANopen device.
 */


#ifndef OBJECTS_H
# define OBJECTS_H	1

/** \struct PDO_MAPPING8_T;
 * \brief PDO mapping structure for 8 mapping entries
 */
typedef struct {
    UNSIGNED8	numOfEntries;	/**< number of entries */
    UNSIGNED32	map[8];	/**< mapping entries */
} PDO_MAPPING8_T;

/* Note: The data types STORAGE1_T .. STORAGE8_T are defined in co_stor.h. */


/* Declaration of Variables (Maintenance) */

extern CO_DT_INIT_VAR UNSIGNED16	 maxObjDicElements;

/* Declaration of Variables (Device Objects) */

#ifdef CONFIG_EXTERN_COMMUNICATION_PARAMETER
extern CO_DT_INIT_VAR UNSIGNED32	p301_device_type;
extern CO_DT_INIT_VAR UNSIGNED8	p301_error_register;
extern CO_DT_INIT_VAR UNSIGNED32	p301_cob_id_sync;
extern CO_DT_INIT_VAR VIS_STRING_T	p301_manu_device_name[1];
extern CO_DT_INIT_VAR VIS_STRING_T	p301_manu_hardware_version[1];
extern CO_DT_INIT_VAR VIS_STRING_T	p301_manu_software_version[1];
extern CO_DT_INIT_VAR UNSIGNED16	p301_guard_time;
extern CO_DT_INIT_VAR UNSIGNED8	p301_life_time_factor;
extern CO_DT_INIT_VAR STORAGE3_T	p301_store_para;
extern CO_DT_INIT_VAR UNSIGNED32	p301_hb_consumer[2];
extern CO_DT_INIT_VAR UNSIGNED16	p301_prod_hb_time;
extern CO_DT_INIT_VAR IDENTITY_T	p301_identity;
extern CO_DT_INIT_VAR PDO_COMM_PAR2_T	p301_n1_rpdo_para;
extern CO_DT_INIT_VAR PDO_MAPPING8_T	p301_n1_rpdo_map;
extern CO_DT_INIT_VAR PDO_COMM_PAR2_T	p301_n1_tpdo_para;
extern CO_DT_INIT_VAR PDO_COMM_PAR2_T	p301_n2_tpdo_para;
extern CO_DT_INIT_VAR PDO_MAPPING8_T	p301_n1_tpdo_map;
extern CO_DT_INIT_VAR PDO_MAPPING8_T	p301_n2_tpdo_map;
extern CO_DT_INIT_VAR UNSIGNED8	p302_program_control[3];
#endif /* CONFIG_EXTERN_COMMUNICATION_PARAMETER */
extern CO_DT_INIT_VAR UNSIGNED32	Statistics_Object[4];
extern CO_DT_INIT_VAR INTEGER16	Device_Temperature[2];
extern CO_DT_INIT_VAR UNSIGNED16	Device_error_flags;
extern CO_DT_INIT_VAR UNSIGNED16	Control_Word;
extern CO_DT_INIT_VAR UNSIGNED16	Status_Word;
extern CO_DT_INIT_VAR INTEGER8	Modes_Of_Operation;
extern CO_DT_INIT_VAR INTEGER8	Modes_OperationDisp;
extern CO_DT_INIT_VAR INTEGER32	Position_Actual_Value;
extern CO_DT_INIT_VAR UNSIGNED16	Max_Current;
extern CO_DT_INIT_VAR UNSIGNED32	Motor_Rated_Current;
extern CO_DT_INIT_VAR INTEGER16	Current_Actual_Value;
extern CO_DT_INIT_VAR INTEGER32	Target_Position;


/* Declaration of Value Descriptions */

#ifdef CONFIG_EXTERN_VALUE_DESCRIPTION
extern VALUE_DESC_T	CO_CONST i1000_desc[1];
extern VALUE_DESC_T	CO_CONST i1001_desc[1];
extern VALUE_DESC_T	CO_CONST i1005_desc[1];
extern VALUE_DESC_T	CO_CONST i1008_desc[1];
extern VALUE_DESC_T	CO_CONST i1009_desc[1];
extern VALUE_DESC_T	CO_CONST i100A_desc[1];
extern VALUE_DESC_T	CO_CONST i100C_desc[1];
extern VALUE_DESC_T	CO_CONST i100D_desc[1];
extern VALUE_DESC_T	CO_CONST i1010_desc[4];
extern VALUE_DESC_T	CO_CONST i1016_desc[2];
extern VALUE_DESC_T	CO_CONST i1017_desc[1];
extern VALUE_DESC_T	CO_CONST i1018_desc[5];
extern VALUE_DESC_T	CO_CONST i1400_desc[3];
extern VALUE_DESC_T	CO_CONST i1600_desc[9];
extern VALUE_DESC_T	CO_CONST i1800_desc[3];
extern VALUE_DESC_T	CO_CONST i1801_desc[3];
extern VALUE_DESC_T	CO_CONST i1A00_desc[9];
extern VALUE_DESC_T	CO_CONST i1A01_desc[9];
extern VALUE_DESC_T	CO_CONST i1F51_desc[3];
extern VALUE_DESC_T	CO_CONST i2000_desc[4];
extern VALUE_DESC_T	CO_CONST i2001_desc[2];
extern VALUE_DESC_T	CO_CONST i2100_desc[1];
extern VALUE_DESC_T	CO_CONST i6040_desc[1];
extern VALUE_DESC_T	CO_CONST i6041_desc[1];
extern VALUE_DESC_T	CO_CONST i6060_desc[1];
extern VALUE_DESC_T	CO_CONST i6061_desc[1];
extern VALUE_DESC_T	CO_CONST i6064_desc[1];
extern VALUE_DESC_T	CO_CONST i6073_desc[1];
extern VALUE_DESC_T	CO_CONST i6075_desc[1];
extern VALUE_DESC_T	CO_CONST i6078_desc[1];
extern VALUE_DESC_T	CO_CONST i607A_desc[1];
#endif /*CONFIG_EXTERN_VALUE_DESCRIPTION */

/* Declaration of Object Dictionary */
#ifdef CONFIG_EXTERN_COMMUNICATION_PARAMETER
extern OBJDIR_T	objDir[];
#endif /* CONFIG_EXTERN_COMMUNICATION_PARAMETER */
#endif /* OBJECTS_H*/


/*----------------------------------------------------------------------------*/

